### ISSUE TITLE
Can't seem to disable items

### ISSUE THREAD

**Issue by AUsername-Ye** [shirograhm/TooManyItemsRoR2#12]
Tried deleting the config and letting it regenerate itself then disabling again to no avail. Items still appear in logbook and in the runs themselves.

**Comment by shirograhm** [comment]
Thanks, I will check this out. Can you provide your mod profile code as well?

**Comment by shirograhm** [comment]
Did you toggle the config that enables all custom config values?

**Comment by AUsername-Ye** [comment]
Yeah i'm dumb, that was the issue. Seems to work just fine, my bad.

**Comment by shirograhm** [comment]
No worries, thanks for reaching out!
