### ISSUE TITLE
Prevents void item corruption if certain items are disabled in the config

### ISSUE THREAD

**Issue by aembur** [shirograhm/TooManyItemsRoR2#15]
Steps to reproduce:
1. Create a new r2modman profile.
2. Install TooManyItems and DebugToolkit
3. Launch the game. Default configs will be generated, don't change them yet.
4. Start a new run.
5. Open console with `CTRL + ALT + ~`.
6. Give Will-o'-the-wisp and Voidsent Flame. Should be `give_item 66` and `give_item 67` respectively (or any other pair of normal item + void version).
7. Verify that normal item gets corrupted by the void item.
8. Close the game.
9. In `TooManyItems.cfg` enable custom config, disable every item, and save changes.
10. Launch the game again.
11. Repeat steps 4, 5, and 6 (item IDs will be different: `give_item 54` and `give_item 55`).
12. Verify that the normal item doesn't get corrupted now.

Here's a profile code that you can import to set things up faster: `0190924e-e957-d6ee-fa81-f79875cbcfe4`. I already disabled all items in the `TooManyItems.cfg`, but `Use Custom Config` has been set to `false`.

I'm not sure which set of items cause this to happen when disabled, since it takes a while to test different combinations, but from my testing the set includes at least Thumbtack, Iron Heart, Defiled Heart, Soul Ring, and Shadow Crest.

Oh, and I might as well include this while I'm at it:
The void items Defiled Heart and Shadow Crest don't actually specify which items they corrupt in their descriptions.

**Comment by khdtheryu** [comment]
Can confirm. Ran into the same issue after I disabled couple of items from the mod in the config.

**Comment by shirograhm** [comment]
Sorry, I was on vacation. This is fixed in version 0.4.6.
