### ISSUE TITLE
Items do not properly respect the configuration files

### ISSUE THREAD

**Issue by C6Wanderer** [shirograhm/TooManyItemsRoR2#17]
Hello! I have a relatively large modpack and as part of that modpack's maintenance, I prune items which are duplicates of each other in the mods' configs. However, I couldn't help but notice that even though I have some TooManyItems items filtered out, such as Spirit Stone, Rubber Ducky, and Glass Marbles, that such items continue to exist in my game. Please fix!

**Comment by shirograhm** [comment]
Hi, sorry for the delay. There is a setting called something like "use custom values" at the top of the config file that tells the mod to respect the file's settings, has that been turned on? I can debug later tonight when I am home.

**Comment by shirograhm** [comment]
Closing as I cannot recreate it without using the "Use custom values" setting.
