### ISSUE TITLE
Nothing Takes Damage?

### ISSUE THREAD

**Issue by Icpwee** [shirograhm/TooManyItemsRoR2#19]
Once you load into a game and try to hit something you deal no damage and the atk effect plays a bunch. You also don't take any damage and glancing blows seem to deflect. This is probably just the SoTS being Bochy code but I figured that id report it.

**Comment by shirograhm** [comment]
You are right, the mod has not been updated for SotS yet. There will be a version 0.5.0 released today to fix this bug.

**Comment by shirograhm** [comment]
Closing this issue now that v0.5.0 has been released. Please try that new version and let me know if any bugs arise.
