### ISSUE TITLE
Fleece Hoodie applies to shield recharge timer

### ISSUE THREAD

**Issue by cesmaster644** [shirograhm/TooManyItemsRoR2#2]
I can only assume that it could apply to other similar "buffs"/"debuffs" that are used as timers like that, but I noticed that it will actually _increase_ your shield recharge delay if that's the next "buff" you get while it's off cooldown.

**Comment by shirograhm** [comment]
I need more detail for this. Can you give me more detail on the situation in which this bug happened (what shield you mean, items in inventory, survivor played)? I tested the Void DLC Safer Spaces shield as well as the generic Shield Generator while out-of-combat and could not reproduce any issue.

**Comment by shirograhm** [comment]
I am closing this as I cannot reproduce it.
