### ISSUE TITLE
Shields Have No Delay Before Regenerating

### ISSUE THREAD

**Issue by shirograhm** [shirograhm/TooManyItemsRoR2#21]
Shields regenerate instantly. This is not intended.

**Comment by Aaronishy** [comment]
Oddly Shaped Opal also doesnt go away when you are damaged, I havent tested other "out of combat" effects but saying a similar issue is happening with shield, it might be all out of combat effects.

**Comment by shirograhm** [comment]
Identified bug with Broken Mask causing out of combat effects to trigger instantly. This will be fixed in a patch (v0.5.1) within the next few hours.

**Comment by shirograhm** [comment]
Closing now that hotfix v0.5.1 was released.
