### ISSUE TITLE
Null reference on item load

### ISSUE THREAD

**Issue by ashank1** [shirograhm/TooManyItemsRoR2#26]
Tried running 0.5.1 without any other mods, loading stops at 99%, this is the error log, seems that the Iron Heart item is not loading properly, did try to remove the mod. 
Disabling the item specified in error log though custom config just points it to another, item, removing all items fixes it but at that point the mod might be disabled
[Error  : Unity Log] TypeLoadException: Could not load type of field 'R2API.DamageAPI:damageTypeHolders' (2) due to: Could not resolve type with token 01000018 from typeref (expected class 'RoR2BepInExPack.Utilities.FixedConditionalWeakTable`2' in assembly 'RoR2BepInExPack, Version=1.7.0.0, Culture=neutral, PublicKeyToken=null') assembly:RoR2BepInExPack, Version=1.7.0.0, Culture=neutral, PublicKeyToken=null type:RoR2BepInExPack.Utilities.FixedConditionalWeakTable`2 member:(null)
Stack trace:
TooManyItems.IronHeart.Init () (at <596bfd320e8b4757903d9a4f39cb977b>:IL_0025)
TooManyItems.TooManyItems.Awake () (at <596bfd320e8b4757903d9a4f39cb977b>:IL_00D8)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
RoR2.Console:.cctor()

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
RoR2.ItemDef+Pair.GetHashCode () (at <16cc1fce0293407eb57af2430f30cf55>:IL_0000)
System.Collections.Generic.GenericEqualityComparer`1[T].GetHashCode (T obj) (at <7e05db41a20b45108859fa03b97088d4>:IL_000A)
System.Linq.Set`1[TElement].InternalGetHashCode (TElement value) (at <06cfd796a56e417bab3ed4200b0661b2>:IL_0008)
System.Linq.Set`1[TElement].Add (TElement value) (at <06cfd796a56e417bab3ed4200b0661b2>:IL_0000)
System.Linq.Set`1[TElement].UnionWith (System.Collections.Generic.IEnumerable`1[T] other) (at <06cfd796a56e417bab3ed4200b0661b2>:IL_0010)
System.Linq.Enumerable+UnionIterator`1[TSource].FillSet () (at <06cfd796a56e417bab3ed4200b0661b2>:IL_001B)
System.Linq.Enumerable+UnionIterator`1[TSource].ToArray () (at <06cfd796a56e417bab3ed4200b0661b2>:IL_0000)
System.Linq.Enumerable.ToArray[TSource] (System.Collections.Generic.IEnumerable`1[T] source) (at <06cfd796a56e417bab3ed4200b0661b2>:IL_001F)
TooManyItems.TooManyItems+<>c.<InjectVoidItemTramsforms>b__11_0 (On.RoR2.Items.ContagiousItemManager+orig_Init orig) (at <596bfd320e8b4757903d9a4f39cb977b>:IL_013D)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<RoR2.Items.ContagiousItemManager::Init>?1268067424()
System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <7e05db41a20b45108859fa03b97088d4>:IL_006A)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <7e05db41a20b45108859fa03b97088d4>:IL_0083)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <7e05db41a20b45108859fa03b97088d4>:IL_0000)
RoR2BepInExPack.VanillaFixes.FixSystemInitializer+<LogBadCycle>d__3.MoveNext () (at <dcfd801117434c69ad117b0772e91f5f>:IL_022A)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <a20b3695b7ce4017b7981f9d06962bd1>:IL_0026)

**Comment by shirograhm** [comment]
Did you run this with R2API_DamageType?

**Comment by shirograhm** [comment]
I created a new profile in Thunderstore, only added TooManyItems v0.5.1, and was unable to reproduce this issue. Can you link your mod list and let me know if you have the SotV DLC? That could be causing an issue.

**Comment by ashank1** [comment]
> Did you run this with R2API_DamageType? It's part of R2API dependencies that are installed when this mod is installed through Thunderstore.

Yes, disabled all of my mods and re-enabled TMI only, so all 30 dependencies and TMI itself was enabled.
I do have SotV
Running separate profile with 0.5.1 gives same result, at this rate I might just reinstall the game

Modlist code: 0191d5db-5852-c0db-e402-175155ae42bc

**Comment by shirograhm** [comment]
Using your modlist's code I am able to import the code to a new profile and run the game without any updates.
![image](https://github.com/user-attachments/assets/863b3762-7c14-48e4-aeda-f7ec7736cd8a)
![image](https://github.com/user-attachments/assets/ad9e45b7-c72a-448e-ab0d-3a315833ae64)

I was even able to pick up items from TMI.
![image](https://github.com/user-attachments/assets/b8f377b0-3ce6-41b3-a63c-6ad8d4690744)

I noticed there are a lot of deprecated/disabled mods in your modlist; I would recommend removing those and/or their config files, that might help. Otherwise it could be an issue with Thunderstore, in which case deleting the old profile and creating a new one (using the code above, even) may fix it.

It also seems like the above DamageType bug is originating from the UpcapAttackSpeed mod, but I'm not sure why that is.
![image](https://github.com/user-attachments/assets/baf39a8e-9c21-4278-8afa-c2b51ea0a630)

Finally, even though I was able to load into the game, mods like EmptyChestsBeGone, ShowDeathCause, BazaarExpand, Infinite_Shrine_of_the_Mountain, and EasyLocateTeleporter have not been updated for the SotS release. I would recommend finding alternatives to these mods (and any others that do not have SotS releases).

**Comment by ashank1** [comment]
> Using your modlist's code I am able to import the code to a new profile and run the game without any updates. 
> 
> I was even able to pick up items from TMI. 
> 
> I noticed there are a lot of deprecated/disabled mods in your modlist; I would recommend removing those and/or their config files, that might help. Otherwise it could be an issue with Thunderstore, in which case deleting the old profile and creating a new one (using the code above, even) may fix it.
> 
> It also seems like the above DamageType bug is originating from the UpcapAttackSpeed mod, but I'm not sure why that is. !
> 
> Finally, even though I was able to load into the game, mods like EmptyChestsBeGone, ShowDeathCause, BazaarExpand, Infinite_Shrine_of_the_Mountain, and EasyLocateTeleporter have not been updated for the SotS release. I would recommend finding alternatives to these mods (and any others that do not have SotS releases).

I wiped my game proper and used a new list so I don't have the issue now, The UpcappAttackSpeed mod is for commando (My main), removes the attack speed lock that is in the game, pre SotS mods did work for me allright as these don't interfere with anything new.

Can you do a short explanation on how you found out what actually caused the issue? would save me posting issues like this in future.

**Comment by shirograhm** [comment]
Well, I still don't know what initially caused this bug, and I think it was valid to post an issue about this. What I did was just import your modlist from the code into a new profile, and then run it as-is. It seems like this could have been a configuration issue with Thunderstore, as creating a new profile prevented me (or you) from recreating the bug that you got at 99%. I've had similar issues with modlists in Thunderstore in the past, and could not find a fix outside of re-installing the game (or creating a fresh modlist). That being said, I don't know for sure.

I am glad you were able to get the issue resolved! If you ever have issues like this in the future, don't hesitate to reach out.
