### ISSUE TITLE
Items disabled in config show up in game

### ISSUE THREAD

**Issue by kicknrekka** [shirograhm/TooManyItemsRoR2#30]
As the title says, even if the items are disabled via the r2modman mod config, they'll still show up in game. Assuming this is a SOTV related issue and didn't see it mentioned yet. Thanks

**Comment by shirograhm** [comment]
Hi, did you enable the "Use Custom Config" toggle at the top of the config file? The mod will not consider your config changes unless you enable that toggle.

**Comment by shirograhm** [comment]
Closing this issue since I cannot recreate it without disabling the "Use Custom Config" setting.
