### ISSUE TITLE
About Translation

### ISSUE THREAD

**Issue by MushroomEl** [shirograhm/TooManyItemsRoR2#5]
Hello author, I created the language file of this mod through the 'LanguageFileGenerator' mod and translated it into Chinese.
This is the language file created by the mod and the file I translated into Chinese.
I created a 'language' folder in your mod folder, just put it in and it will work.
Translations to other languages ​​should be possible using this method.
[Desktop.zip](https://github.com/user-attachments/files/15522150/Desktop.zip)

**Comment by shirograhm** [comment]
I am re-coding the language files for 0.3.7, please see here: https://github.com/shirograhm/TooManyItemsRoR2/blob/0.3.7/TooManyItems/Lang/en.language

If you could redo the translations using this file, that would be very helpful. Just don't translate anything inside <> or { }. I tried to redo the file you sent in the ZIP, but I cannot read Chinese.

**Comment by MushroomEl** [comment]
I translated the language file you gave me. I have translated such files many times before, so it should be no problem.
[zh-CN.zip](https://github.com/user-attachments/files/15614436/zh-CN.zip)

I noticed that there seems to be some new content. I will continue to pay attention to your mod and update the translation.

**Comment by shirograhm** [comment]
Thank you. the Vanity item will likely change, so I may need one more update this weekend. In the meantime I will commit this to the github repo, please dont hesitate to make a PR or message me on discord @shirograhm if you notice any differences
